class InvalidCellValueError(Exception): ...
class OccupiedCellError(Exception): ...
class InvalidOperandError(Exception): ...
class InvalidTokenError(Exception): ...
class InvalidCellCoordinateError(Exception): ...
